export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor:"Lightblue",
            padding:"1rem",
          }}
          >
          
          <p>header</p>
            </header>
            {children}
            <footer>
              <p>
                Footer</p>
            </footer></body>
    </html>
  )
}
